# Generated by Django 2.1.5 on 2019-03-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodPreferences', models.CharField(max_length=1000)),
                ('allergens', models.CharField(max_length=1000)),
            ],
        ),
    ]
